### ISSUE TITLE
What is the difference between two different FPGA MIPI CSI 2 receivers 

### ISSUE THREAD

**Issue by cliffchar** [circuitvalley/mipi_csi_receiver_FPGA#2]
Hello,
You have two different repo one is this mipi_csi_receiver_FPGA and another is USB_C_Industrial_Camera_FPGA_USB3 I an wondering what is the difference between them? They both do same function?

**Comment by circuitvalley** [comment]
yes both of the implementations  achieve the same goal of  Implementing MIPI CSI 2 receiver on FPGA and making a USB3 camera out of it. mipi_csi_receiver_FPGA is old design and first version of the same implementation while USB_C_Industrial_Camera_FPGA_USB3 is more polished on a custom hardware, it has faster properly implemented  and configureable better in every way.

I suggest every one to use and reference only  USB_C_Industrial_Camera_FPGA_USB3 .
